project_name: firehose-antelope

release:
  github:
    owner: streamingfast
    name: firehose-antelope
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  - darwin
  goarch:
  - arm64
  - amd64
  targets:
  - linux_amd64
  - darwin_amd64
  - darwin_arm64
  main: ./cmd/fireantelope
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: fireantelope
  env:
  - CGO_ENABLED=0
archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    amd64: x86_64
    darwin: macOS
    linux: linux
  format: tar.gz
  files:
  - LICENSE
  - README.md
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: dist
signs:
- cmd: keybase
  args:
  - sign
  - --infile
  - $artifact
  - --binary
  - --outfile
  - $signature
  - --detached
  signature: ${artifact}.sig
  artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
#brews:
#  - name: firehose-antelope
#    tap:
#      owner: Pinax
#      name: homebrew-tap
#    commit_author:
#      name: goreleaserbot
#      email: goreleaser@eosnation.io
#    homepage: "https://github.com/pinax-network/firehose-antelope"
#    description: "Firehose on Antelope stack"
#    license: "Apache-2.0"
