// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.7
// source: sf/antelope/transform/v1/transforms.proto

package pbtransform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CombinedFilter is a combination of "LogFilters" and "CallToFilters"
//
// It transforms the requested stream in two ways:
//   1. STRIPPING
//      The block data is stripped from all transactions that don't
//      match any of the filters.
//
//   2. SKIPPING
//      If an "block index" covers a range containing a
//      block that does NOT match any of the filters, the block will be
//      skipped altogether, UNLESS send_all_block_headers is enabled
//      In that case, the block would still be sent, but without any
//      transactionTrace
//
// The SKIPPING feature only applies to historical blocks, because
// the "block index" is always produced after the merged-blocks files
// are produced. Therefore, the "live" blocks are never filtered out.
//
type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionFilters []*ActionFilter `protobuf:"bytes,1,rep,name=action_filters,json=actionFilters,proto3" json:"action_filters,omitempty"`
	// Always send all blocks. if they don't match any log_filters or call_filters,
	// all the transactions will be filtered out, sending only the header.
	SendAllBlockHeaders bool `protobuf:"varint,3,opt,name=send_all_block_headers,json=sendAllBlockHeaders,proto3" json:"send_all_block_headers,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_antelope_transform_v1_transforms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_sf_antelope_transform_v1_transforms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_sf_antelope_transform_v1_transforms_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetActionFilters() []*ActionFilter {
	if x != nil {
		return x.ActionFilters
	}
	return nil
}

func (x *Filter) GetSendAllBlockHeaders() bool {
	if x != nil {
		return x.SendAllBlockHeaders
	}
	return false
}

type ActionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account uint64 `protobuf:"varint,1,opt,name=account,proto3" json:"account,omitempty"` // namespace of the action, for example "eosio.token"
	Action  uint64 `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`   // name of the action, for example "transfer"
}

func (x *ActionFilter) Reset() {
	*x = ActionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_antelope_transform_v1_transforms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionFilter) ProtoMessage() {}

func (x *ActionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sf_antelope_transform_v1_transforms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionFilter.ProtoReflect.Descriptor instead.
func (*ActionFilter) Descriptor() ([]byte, []int) {
	return file_sf_antelope_transform_v1_transforms_proto_rawDescGZIP(), []int{1}
}

func (x *ActionFilter) GetAccount() uint64 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *ActionFilter) GetAction() uint64 {
	if x != nil {
		return x.Action
	}
	return 0
}

type LightBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LightBlock) Reset() {
	*x = LightBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sf_antelope_transform_v1_transforms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightBlock) ProtoMessage() {}

func (x *LightBlock) ProtoReflect() protoreflect.Message {
	mi := &file_sf_antelope_transform_v1_transforms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightBlock.ProtoReflect.Descriptor instead.
func (*LightBlock) Descriptor() ([]byte, []int) {
	return file_sf_antelope_transform_v1_transforms_proto_rawDescGZIP(), []int{2}
}

var File_sf_antelope_transform_v1_transforms_proto protoreflect.FileDescriptor

var file_sf_antelope_transform_v1_transforms_proto_rawDesc = []byte{
	0x0a, 0x29, 0x73, 0x66, 0x2f, 0x61, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x73, 0x66, 0x2e,
	0x61, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x76, 0x31, 0x22, 0x8c, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x4d, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x66, 0x2e, 0x61, 0x6e,
	0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x33, 0x0a, 0x16, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x13, 0x73, 0x65, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x22, 0x40, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x0c, 0x0a, 0x0a, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x57, 0x5a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x45, 0x4f, 0x53, 0x2d, 0x4e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x66, 0x69,
	0x72, 0x65, 0x68, 0x6f, 0x73, 0x65, 0x2d, 0x61, 0x6e, 0x74, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x66, 0x2f, 0x65, 0x74, 0x68, 0x65,
	0x72, 0x65, 0x75, 0x6d, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x76,
	0x31, 0x3b, 0x70, 0x62, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sf_antelope_transform_v1_transforms_proto_rawDescOnce sync.Once
	file_sf_antelope_transform_v1_transforms_proto_rawDescData = file_sf_antelope_transform_v1_transforms_proto_rawDesc
)

func file_sf_antelope_transform_v1_transforms_proto_rawDescGZIP() []byte {
	file_sf_antelope_transform_v1_transforms_proto_rawDescOnce.Do(func() {
		file_sf_antelope_transform_v1_transforms_proto_rawDescData = protoimpl.X.CompressGZIP(file_sf_antelope_transform_v1_transforms_proto_rawDescData)
	})
	return file_sf_antelope_transform_v1_transforms_proto_rawDescData
}

var file_sf_antelope_transform_v1_transforms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sf_antelope_transform_v1_transforms_proto_goTypes = []interface{}{
	(*Filter)(nil),       // 0: sf.antelope.transform.v1.Filter
	(*ActionFilter)(nil), // 1: sf.antelope.transform.v1.ActionFilter
	(*LightBlock)(nil),   // 2: sf.antelope.transform.v1.LightBlock
}
var file_sf_antelope_transform_v1_transforms_proto_depIdxs = []int32{
	1, // 0: sf.antelope.transform.v1.Filter.action_filters:type_name -> sf.antelope.transform.v1.ActionFilter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sf_antelope_transform_v1_transforms_proto_init() }
func file_sf_antelope_transform_v1_transforms_proto_init() {
	if File_sf_antelope_transform_v1_transforms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sf_antelope_transform_v1_transforms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_antelope_transform_v1_transforms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sf_antelope_transform_v1_transforms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sf_antelope_transform_v1_transforms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_antelope_transform_v1_transforms_proto_goTypes,
		DependencyIndexes: file_sf_antelope_transform_v1_transforms_proto_depIdxs,
		MessageInfos:      file_sf_antelope_transform_v1_transforms_proto_msgTypes,
	}.Build()
	File_sf_antelope_transform_v1_transforms_proto = out.File
	file_sf_antelope_transform_v1_transforms_proto_rawDesc = nil
	file_sf_antelope_transform_v1_transforms_proto_goTypes = nil
	file_sf_antelope_transform_v1_transforms_proto_depIdxs = nil
}
